server:
  port: 8389
  
# Oracle Connect
spring:
  datasource:
    url:  jdbc:oracle:thin:@localhost:1521/xe
    username: scottjpa
    password: tiger
    driver-class-name:  oracle.jdbc.driver.OracleDriver

  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update  # none create
    properties:
      hibernate:
        default_batch_fetch_size: 500
      show_sql: true  # System에서 hibernate 실행 SQL
      format_sql: true
      
logging.level:
  org.hibernate.SQL:  debug # logger를 통해 하이버네이트 실행 SQL